//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksSalesEditor.AdventureWorksService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrderHeader", Namespace="http://schemas.datacontract.org/2004/07/AdventureWorksService")]
    [System.SerializableAttribute()]
    public partial class SalesOrderHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BillToAddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditCardApprovalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FreightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OnlineOrderFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurchaseOrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte RevisionNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalesOrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalesOrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ShipDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ShipToAddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SubTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TaxAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalDueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid rowguidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BillToAddressID {
            get {
                return this.BillToAddressIDField;
            }
            set {
                if ((this.BillToAddressIDField.Equals(value) != true)) {
                    this.BillToAddressIDField = value;
                    this.RaisePropertyChanged("BillToAddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditCardApprovalCode {
            get {
                return this.CreditCardApprovalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditCardApprovalCodeField, value) != true)) {
                    this.CreditCardApprovalCodeField = value;
                    this.RaisePropertyChanged("CreditCardApprovalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((this.DueDateField.Equals(value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Freight {
            get {
                return this.FreightField;
            }
            set {
                if ((this.FreightField.Equals(value) != true)) {
                    this.FreightField = value;
                    this.RaisePropertyChanged("Freight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OnlineOrderFlag {
            get {
                return this.OnlineOrderFlagField;
            }
            set {
                if ((this.OnlineOrderFlagField.Equals(value) != true)) {
                    this.OnlineOrderFlagField = value;
                    this.RaisePropertyChanged("OnlineOrderFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PurchaseOrderNumber {
            get {
                return this.PurchaseOrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchaseOrderNumberField, value) != true)) {
                    this.PurchaseOrderNumberField = value;
                    this.RaisePropertyChanged("PurchaseOrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte RevisionNumber {
            get {
                return this.RevisionNumberField;
            }
            set {
                if ((this.RevisionNumberField.Equals(value) != true)) {
                    this.RevisionNumberField = value;
                    this.RaisePropertyChanged("RevisionNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalesOrderID {
            get {
                return this.SalesOrderIDField;
            }
            set {
                if ((this.SalesOrderIDField.Equals(value) != true)) {
                    this.SalesOrderIDField = value;
                    this.RaisePropertyChanged("SalesOrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesOrderNumber {
            get {
                return this.SalesOrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesOrderNumberField, value) != true)) {
                    this.SalesOrderNumberField = value;
                    this.RaisePropertyChanged("SalesOrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ShipDate {
            get {
                return this.ShipDateField;
            }
            set {
                if ((this.ShipDateField.Equals(value) != true)) {
                    this.ShipDateField = value;
                    this.RaisePropertyChanged("ShipDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipMethod {
            get {
                return this.ShipMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipMethodField, value) != true)) {
                    this.ShipMethodField = value;
                    this.RaisePropertyChanged("ShipMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ShipToAddressID {
            get {
                return this.ShipToAddressIDField;
            }
            set {
                if ((this.ShipToAddressIDField.Equals(value) != true)) {
                    this.ShipToAddressIDField = value;
                    this.RaisePropertyChanged("ShipToAddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SubTotal {
            get {
                return this.SubTotalField;
            }
            set {
                if ((this.SubTotalField.Equals(value) != true)) {
                    this.SubTotalField = value;
                    this.RaisePropertyChanged("SubTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaxAmt {
            get {
                return this.TaxAmtField;
            }
            set {
                if ((this.TaxAmtField.Equals(value) != true)) {
                    this.TaxAmtField = value;
                    this.RaisePropertyChanged("TaxAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalDue {
            get {
                return this.TotalDueField;
            }
            set {
                if ((this.TotalDueField.Equals(value) != true)) {
                    this.TotalDueField = value;
                    this.RaisePropertyChanged("TotalDue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid {
            get {
                return this.rowguidField;
            }
            set {
                if ((this.rowguidField.Equals(value) != true)) {
                    this.rowguidField = value;
                    this.RaisePropertyChanged("rowguid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdventureWorksService.IAdventureWorksService")]
    public interface IAdventureWorksService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksService/GetOrders", ReplyAction="http://tempuri.org/IAdventureWorksService/GetOrdersResponse")]
        AdventureWorksSalesEditor.AdventureWorksService.SalesOrderHeader[] GetOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksService/GetOrders", ReplyAction="http://tempuri.org/IAdventureWorksService/GetOrdersResponse")]
        System.Threading.Tasks.Task<AdventureWorksSalesEditor.AdventureWorksService.SalesOrderHeader[]> GetOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksService/UpdateOrder", ReplyAction="http://tempuri.org/IAdventureWorksService/UpdateOrderResponse")]
        void UpdateOrder(AdventureWorksSalesEditor.AdventureWorksService.SalesOrderHeader order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksService/UpdateOrder", ReplyAction="http://tempuri.org/IAdventureWorksService/UpdateOrderResponse")]
        System.Threading.Tasks.Task UpdateOrderAsync(AdventureWorksSalesEditor.AdventureWorksService.SalesOrderHeader order);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdventureWorksServiceChannel : AdventureWorksSalesEditor.AdventureWorksService.IAdventureWorksService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdventureWorksServiceClient : System.ServiceModel.ClientBase<AdventureWorksSalesEditor.AdventureWorksService.IAdventureWorksService>, AdventureWorksSalesEditor.AdventureWorksService.IAdventureWorksService {
        
        public AdventureWorksServiceClient() {
        }
        
        public AdventureWorksServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdventureWorksServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdventureWorksServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdventureWorksServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AdventureWorksSalesEditor.AdventureWorksService.SalesOrderHeader[] GetOrders() {
            return base.Channel.GetOrders();
        }
        
        public System.Threading.Tasks.Task<AdventureWorksSalesEditor.AdventureWorksService.SalesOrderHeader[]> GetOrdersAsync() {
            return base.Channel.GetOrdersAsync();
        }
        
        public void UpdateOrder(AdventureWorksSalesEditor.AdventureWorksService.SalesOrderHeader order) {
            base.Channel.UpdateOrder(order);
        }
        
        public System.Threading.Tasks.Task UpdateOrderAsync(AdventureWorksSalesEditor.AdventureWorksService.SalesOrderHeader order) {
            return base.Channel.UpdateOrderAsync(order);
        }
    }
}
